### ISSUE TITLE
Right-Hand Justified possible?

### ISSUE THREAD

**Issue by ArcAIN6** [nickgammon/bitBangedSPI#1]
I've been using this library for a few weeks now, and i do like how easy it is to implement, however, in the case of displaying numbers across several displays, it can be a tad inconvenient for the user. 

In my particular case, i'm useing three 8-digit modules as a DRO for my CNC machine, the issue that commonly happens, is it's counter-intuitive to decipher the display's output easily and quickly. i.e. 
Reading the display shows:
```
X:-421.655
Y:-1.250
Z:157.155
```

In my particular case, because the modules are stacked on on top of the other to conserve housing space, a better method would be to justify the digits to the right-hand side,  allowing for an intuitive "at a glance" reading of the display, instead of having to really think about the displayed numbers. Basically, keeping the decimal point aligned, allows for faster understanding of the positional data displayed. 
Example:
Reading a right-justified display:

```
X: -421.655
Y:   -1.250
Z:  157.155
```

My question is, is it possible to edit / alter the library to look at the character count given to it, and offset to display the alphanumeric content on the right-hand side of the display, and fill any remaining space with nothing?

**Comment by nickgammon** [comment]
The library simply sends stuff to the display. Formatting it is out of its purview. I suggest that you can fix up the justification by simply writing to a temporary buffer using `sprintf` and then sending that buffer to the display. Using `sprintf` you can pad out the numeric fields to the required width.

Having said that, `sprintf` doesn't handle floats on the normal Arduino platform. So you can pre-format the floating-point numbers like this:

``` c++
  float f = 42.56;
  char buf [20];
  dtostrf (f, 10, 4, buf);  // number, width, decimal places, buffer
```

Using `dtostrf` (double to string) you can control the width of the field, and the number of decimal places.

**Comment by ArcAIN6** [comment]
thank you for the idea, i'm off to tinker to get that method wedged into my code.
