### ISSUE TITLE
SPI Slave Mode

### ISSUE THREAD

**Issue by Miguel0101** [nickgammon/bitBangedSPI#2]
I'm currently developing a project that involves two ATMega328p (master and slave) and an SD card module (it's in the slave's code). The slave code does not receive the data correctly, possibly it is the SD that does not enter the high impedance mode when disabled. I thought of simply using your library that doesn't use the hardware SPI pins since I won't have problems with the SD card (hardware SPI). But I don't know how to put it in slave mode, I would like help :)

**Comment by X-Genesis-Qhulut** [comment]
> I don't know how to put it in slave mode ...

What do you mean by "it"? The bitbanged SPI code is only designed to be used as a master. I have a [temperature and humidity sensor](https://www.gammon.com.au/forum/?id=12106) which has an SD card which uses hardware SPI, and also drives a 7-segment display which uses bit-banged SPI.

Perhaps that will give you some ideas.

**Comment by nickgammon** [comment]
> I don't know how to put it in slave mode ...

What do you mean by "it"? The bitbanged SPI code is only designed to be used as a master. I have a [temperature and humidity sensor](https://www.gammon.com.au/forum/?id=12106) which has an SD card which uses hardware SPI, and also drives a 7-segment display which uses bit-banged SPI.

Perhaps that will give you some ideas.

**Comment by Miguel0101** [comment]
I took a look at your code and it really doesn't support SPI software in slave mode. I apologize for the misunderstanding. I would like to understand why the MISO pin of my SD module does not go into high impedance when its SS is high. I thank.

**Comment by nickgammon** [comment]
This is not really a question related to this software. I suggest you ask it on [Arduino Stack Exchange](https://arduino.stackexchange.com/) or [Electronics Stack Exchange](https://electronics.stackexchange.com/).
